---
page-layout: full
toc: false
---

# About El Aleph

"El Aleph" is a short story by Jorge Luis Borges. It describles a point in space that contains all other spaces at once. Anyone who gazes into it can see everything in the universe from every angle simultaneously, without distortion, overlapping, or confusion. Aleph can not be described, one can only feel it. Based on the quote **never stop learning**, El Aleph is chosen as the name of this website.

# About Me

#### Experience
* 2022 - now: Application Engineer | Infineon AG
* 2020 - 2022: Student Assistant | Chair of Power Electronics | University of Technology Chemnitz

#### Publication
* Influence of Magnetic Coupling Effects between Load and Gate Commutation Loop on the Short Circuit Behavior
* Temperatur Distribution of an IGBT Chip during Repetitive Switching Events under Consideration of Front-Side Aging

#### Education
* 2019 - 2022: University of Technology Chemnitz | Master of Electro-Mobility
* 2018 - 2019: University of Technology Chemnitz | Bachelor of Electro-Mobility
* 2012 - 2016: Shandong University of Technology | Bachelor of Transportation and Communication